
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for cake
-- ----------------------------
DROP TABLE IF EXISTS `cake`;
CREATE TABLE `cake`  (
  `id` int(3) NULL DEFAULT NULL,
  `name` varchar(10) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `engname` varchar(30) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `introduce` varchar(10) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `price` int(5) NULL DEFAULT NULL,
  `weight` varchar(20) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `img` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `posiImg` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `count` int(3) NULL DEFAULT NULL,
  `thiscount` int(3) NULL DEFAULT NULL,
  `total` int(5) NULL DEFAULT NULL,
  `dataOnline` varchar(10) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `dataItem` varchar(10) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `introduceText` varchar(100) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  `dataImg` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = gbk COLLATE = gbk_chinese_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of cake
-- ----------------------------
INSERT INTO `cake` VALUES (1, '深爱', 'Deep Bailey Lovers', '你深爱过吗？', 268, '454g(1.0磅)', './img/contItem1.jpg', './img/mingxing.png', 1, 1, 99, 'online', 'cake', '/奶油中调入玫瑰甘露，整体色泽加深/<br>/夹心中增加可咀嚼的玫瑰蜜饯，丰富口感/<br>*玫瑰花瓣经过消毒处理，仅用作装饰使用（使用围边纸与蛋糕隔开），不可食用。<br>1月1日起夹心为草莓。', NULL);
INSERT INTO `cake` VALUES (2, '草莓奶油蛋糕', 'Strawberry Cream Cake', '你深爱过吗？', 228, '908g(2.0磅)', './img/contItem2.jpg', './img/shiling.png', 1, 1, 99, 'online', 'cake', '/草莓配奶油，从王室，前往温布尔登的雨季/<br>Now 21cake has encapsulated this gloriously English tradition in square cak', NULL);
INSERT INTO `cake` VALUES (3, '黑越橘', 'Blue Monday', '你深爱过吗？', 298, '908g(2.0磅)', './img/contItem3.jpg', './img/shiling.png', 1, 1, 99, 'online', 'cake', '/从苏必利尔湖西端，至安大略湖东端的1400公里，是北美五大湖所经流域/<br>/这里，是黑越橘（野生蓝莓）的天堂/<br>Got those Monday blues? It’s time for ', NULL);
INSERT INTO `cake` VALUES (4, '布莱克', 'The Nut Job Big', '你深爱过吗？', 298, '908g(2.0磅)', './img/contItem4.jpg', './img/shiling.png', 1, 1, 99, 'online', 'cake', '/比利时黑巧克力与中国榛子，淡苦与干脆，浓香丰满/<br>Crazily crisp dark chocolate and kookily nutty fist fulls of Chinese ha', NULL);
INSERT INTO `cake` VALUES (5, '（新）卡百利（丰香奶', 'Strawberry Fool', '八个风味层次，让草莓', 268, '454g(1.0磅)', './img/contItem5.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '产品限量，需提前预定', NULL);
INSERT INTO `cake` VALUES (6, '榴莲飘飘', 'A Picture of Durian Grey', '八个风味层次，让草莓', 298, '908g(2.0磅)', './img/contItem6.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '/自然成熟的泰国榴莲/<br>/在曼谷，官兵后代庭院中，生长着一百年至一百五十年的榴莲树/<br>Imagine if an object could bear the weight of all y', NULL);
INSERT INTO `cake` VALUES (7, '黑白巧克力慕斯', 'Black and White Chocolate Mous', '八个风味层次，让草莓', 298, '908g(2.0磅)', './img/contItem7.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '/口感冰凉细腻，白巧克力慕斯的甜，与底部黑巧克力酱的苦/<br>Cool, silky white chocolate. Rich, bitter dark chocolate. They’re li', NULL);
INSERT INTO `cake` VALUES (8, '米道', 'Rice Cake', '八个风味层次，让草莓', 298, '454g(1.0磅)', './img/contItem8.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '天真、天然<br>是我们做这款蛋糕唯一的出发点', NULL);
INSERT INTO `cake` VALUES (9, '朗姆芝士', 'Rum Cheese Cake', '八个风味层次，让草莓', 298, '908g(2.0磅)', './img/contItem9.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '/香滑的乳酪与打开的一瓶波多黎各朗姆酒/<br>/酒香，微苦，清新的柠檬/<br>Shiver me timbers! Here’s a rum one – but unlike most of it', NULL);
INSERT INTO `cake` VALUES (10, '浅草', 'Teatime', '八个风味层次，让草莓', 298, '908g(2.0磅)', './img/contItem10.jpg', './img/mingxing.png', 1, 1, 99, 'online', 'cake', '/“浅草才能没马蹄”/<br>/切着吃的雨前西湖龙井/<br>/中国绿茶与爽脆果实，工笔勾勒一杯好茶/<br>/复杂而纯粹的深浅绿意/', NULL);
INSERT INTO `cake` VALUES (11, '摩卡', 'Café Mocha', '你深爱过吗？', 268, '454g(1.0磅)', './img/contItem11.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '/世上还有摩卡，就有无尽挣扎/', NULL);
INSERT INTO `cake` VALUES (12, '（新）栗蓉暗香', 'Chestnut Cream', '八个风味层次，让草莓', 298, '908g(2.0磅)', './img/contItem12.jpg', './img/renqi.png', 1, 1, 99, 'online', 'cake', '/栗子烘烤的蛋糕坯，鲜栗蓉，点缀手工比利时黑巧克力豆/<br>Chestnuts and real fresh cream go so well together you know this isn’', NULL);
INSERT INTO `cake` VALUES (13, '桂圆冰淇淋蛋糕', 'Ice Cream Cake with Longan', '八个风味层次，让草莓', 298, '908g(2.0磅)', './img/contItem12.jpg', 'null', 1, 1, 99, 'LowerShelf', 'cake', '/栗子烘烤的蛋糕坯，鲜栗蓉，点缀手工比利时黑巧克力豆/<br>Chestnuts and real fresh cream go so well together you know this isn’', NULL);
INSERT INTO `cake` VALUES (14, '原味牛乳冰淇淋', 'Milk Gelato', '八个风味层次，让草莓', 45, '80g(盒)', './img/ice1.jpg', 'null', 1, 1, 99, 'online', 'IceCream', '/纯正牛乳，牛乳香，单纯/<br>/Gelato10自研，新西兰乳脂奶油/<br>/融入鲜奶，单纯之能及/', NULL);
INSERT INTO `cake` VALUES (15, '夏日-Affogat', 'Affogato', '八个风味层次，让草莓', 55, '80g(份)', './img/ice2.jpg', 'null', 1, 1, 99, 'online', 'IceCream', '/Affogato，冰淇淋吃法的一次实践/<br>/现冲，水粉比12:1 。约120ml，90℃-95℃热水冲煮挂耳咖啡/<br>/打开Gelato10，将咖啡注入冰淇淋表面/<br>/倒入少量，是咖', NULL);
INSERT INTO `cake` VALUES (16, '荔枝冰淇淋', 'Litchi Gelato', '八个风味层次，让草莓', 45, '80g(盒)', './img/ice3.jpg', 'null', 1, 1, 99, 'LowerShelf', 'IceCream', '/丰富，真实/<br>/小众口味荔枝冰淇淋/<br>/少见的口味，少见的工艺/<br>/每盒gelato10，荔枝冰淇淋/<br>/使用超过35%荔枝食材/<br>/而非浓缩调味汁 /<br>/荔枝香', NULL);
INSERT INTO `cake` VALUES (17, '拿铁冰淇淋', 'Latte Gelato', '八个风味层次，让草莓', 45, '80g(盒)', './img/ice4.jpg', 'null', 1, 1, 99, 'LowerShelf', 'IceCream', '/日晒与水洗西达摩拼配，香气浓郁/<br>/中偏深烘焙，带来巧克力坚果气息，和烟熏尾韵/<br>/咖啡加牛奶，平衡、醇厚/<br>', NULL);
INSERT INTO `cake` VALUES (18, '蔓越莓干（1包）', 'null', '八个风味层次，让草莓', 45, '244g(份)', './img/cafe6.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/日晒与水洗西达摩拼配，香气浓郁/<br>/中偏深烘焙，带来巧克力坚果气息，和烟熏尾韵/<br>/咖啡加牛奶，平衡、醇厚/<br>', NULL);
INSERT INTO `cake` VALUES (19, '灰枣（1包）', 'null', '八个风味层次，让草莓', 45, '195g(份)', './img/cafe2.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/产自中国新疆，独一无二树上自然吊干红枣，被誉为“天然维生素丸”，核小，肉质脆厚，富含营养。/', NULL);
INSERT INTO `cake` VALUES (20, '手剥紫皮大腰果（12', 'null', '八个风味层次，让草莓', 50, '120g(份)', './img/cafe1.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/产自越南，保留腰果原衣，浅烘焙加工，食用时去衣，还原更原始果香。/', NULL);
INSERT INTO `cake` VALUES (21, '手剥紫皮大腰果（24', 'null', '八个风味层次，让草莓', 80, '248g(份)', './img/cafe1.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/产自越南，保留腰果原衣，浅烘焙加工，食用时去衣，还原更原始果香。/', NULL);
INSERT INTO `cake` VALUES (22, '耶加雪菲挂耳咖啡', 'Yirgacheffe Coffee', '八个风味层次，让草莓', 10, '10g(包)', './img/cafe3.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/自烘焙G1等级水洗耶加雪菲豆/<br>/烘焙时注意到降低酸度/<br>/得到最适合人类味蕾的甜酸比/<br>/柔和柠檬香、花香、蜂蜜味，扑面而来/', NULL);
INSERT INTO `cake` VALUES (23, '西达摩挂耳咖啡', 'Sidamo Coffee', '八个风味层次，让草莓', 10, '10g(包)', './img/cafe4.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/浅中焙，G1等级日晒西达摩豆/<br>/在降低酸度的同时/<br>/充分激发日晒豆成熟的果酱、发酵香/<br>/可以品尝到，红酒般的滑顺和重量感/', NULL);
INSERT INTO `cake` VALUES (24, '巴西挂耳咖啡', 'Brazil Coffee', '八个风味层次，让草莓', 10, '10g(包)', './img/cafe7.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/烘焙时，以还原产区经典风味为前提/<br>/得到干净、低酸，有醇厚坚果香的咖啡液/<br>/焦糖、巧克力尾韵持久/', NULL);
INSERT INTO `cake` VALUES (25, '巴布亚新几内亚挂耳咖', 'Papua New Guinea Coffee', '八个风味层次，让草莓', 10, '10g(包)', './img/cafe8.jpg', 'null', 1, 1, 99, 'online', 'AfternoonT', '/原豆经过三次水洗发酵，口感干净绵长/<br>/释放草本，与微苦巧克力风味/<br>/烘焙时加上优雅烟熏尾调，很别致/', NULL);
INSERT INTO `cake` VALUES (26, '下午茶套餐(双人分享', 'null', '八个风味层次，让草莓', 124, '一份/3.0磅+', './img/cafe8.jpg', 'null', 1, 1, 99, 'LowerShelf', 'AfternoonT', 'null', NULL);
INSERT INTO `cake` VALUES (27, '经典套餐', 'Classic Set Meal', '八个风味层次，让草莓', 58, '305g(一份)', './img/mianbao1.png', './img/mingxing.png', 1, 1, 99, 'online', 'bread', '北海道吐司*1+果酱*2+原味可颂*1+阳光葡萄卷*1+咖啡*2', NULL);
INSERT INTO `cake` VALUES (28, '儿童套餐', 'Children Set Meal', '八个风味层次，让草莓', 48, '230g(一份)', './img/mianbao2.png', './img/mingxing.png', 1, 1, 99, 'online', 'bread', '核桃派*1+蓝莓可颂*1+阳光葡萄卷*1+果酱*1', NULL);
INSERT INTO `cake` VALUES (29, '全家福套餐', 'Children Set Meal', '八个风味层次，让草莓', 78, '445g(一份)', './img/mianbao3.png', './img/mingxing.png', 1, 1, 99, 'online', 'bread', '北海道吐司*1+果酱*2+原味可颂*1+阳光葡萄卷*1+蓝莓可颂*1+核桃派*1+咖啡*1', NULL);
INSERT INTO `cake` VALUES (30, '《家常面包》（京沪杭', 'Home Style Bread', '八个风味层次，让草莓', 41, '265g(一份)', './img/mianbao4.png', './img/mingxing.png', 1, 1, 99, 'online', 'bread', '北海道吐司1份、蓝莓可颂1个、阳光葡萄卷1个', NULL);
INSERT INTO `cake` VALUES (31, '红糖红枣桂圆软欧（京', 'Brown Sugar, Date And Longan B', '八个风味层次，让草莓', 6, '90g(一份)', './img/mianbao5.png', './img/xinping.png', 1, 1, 99, 'online', 'bread', '/传统红糖搭配新疆红枣，与甜润桂圆干/<br>/熟悉的食材带来甜软、踏实的口感/<br>/比中式点心营养更丰富，非常适合秋冬进补/<br>/家里吃不惯面包的老人/<br>/也可以从尝试【养】开始，养成', NULL);
INSERT INTO `cake` VALUES (32, '北海道吐司（4片/京', 'Hokkaido Toast', '八个风味层次，让草莓', 14, '150g(一份)', './img/mianbao6.png', './img/xinping.png', 1, 1, 99, 'online', 'bread', '北海道吐司1份、蓝莓可颂1个、阳光葡萄卷1个', NULL);
INSERT INTO `cake` VALUES (33, '磅蛋糕切片（核桃）', 'Classic Set Meal', '八个风味层次，让草莓', 8, '30g(份)', './img/dangao1.jpg', 'null', 1, 1, 99, 'online', 'NormalTemp', '/使用fine dining级别原料/<br>/烤制朴素的日常点心/<br>/降至常温后，到手中是恰到好处的温度/<br>/轻松拿捏的形状、分量，更适合随时一口/', NULL);
INSERT INTO `cake` VALUES (34, '磅蛋糕切片（杏仁）', 'Pound cake slice', '八个风味层次，让草莓', 8, '30g(份)', './img/dangao2.jpg', 'null', 1, 1, 99, 'online', 'NormalTemp', '/使用fine dining级别原料/<br>/烤制朴素的日常点心/<br>/降至常温后，到手中是恰到好处的温度/<br>/轻松拿捏的形状、分量，更适合随时一口/', NULL);
INSERT INTO `cake` VALUES (35, '磅蛋糕切片（黑朗姆）', 'Pound cake slice', '八个风味层次，让草莓', 8, '30g(份)', './img/dangao3.jpg', 'null', 1, 1, 99, 'online', 'NormalTemp', '/使用fine dining级别原料/<br>/烤制朴素的日常点心/<br>/降至常温后，到手中是恰到好处的温度/<br>/轻松拿捏的形状、分量，更适合随时一口/', NULL);
INSERT INTO `cake` VALUES (36, '设计师竹纸扇', 'Paper fan', '八个风味层次，让草莓', 38, '把', './img/shejishi1.jpg', 'null', 1, 1, 99, 'online', 'gift', '/竹制扇柄、扇骨，表面碳化工艺/<br>/手工西和麻纸扇面，纹路自然氤氲/<br>/拿在手中，就是一夏幽凉/', NULL);
INSERT INTO `cake` VALUES (37, '方形蜡烛', 'Square candle', '八个风味层次，让草莓', 8, '个', './img/shejishi2.jpg', 'null', 1, 1, 99, 'online', 'gift', 'null', NULL);
INSERT INTO `cake` VALUES (38, '圣诞绿蜡烛', 'Green candle', '八个风味层次，让草莓', 12, '个', './img/shejishi3.jpg', 'null', 1, 1, 99, 'online', 'gift', 'null', NULL);
INSERT INTO `cake` VALUES (39, '21cake餐具套餐', 'Tableware package', '八个风味层次，让草莓', 1, '份', './img/shejishi4.jpg', 'null', 1, 1, 99, 'online', 'gift', 'null', NULL);
INSERT INTO `cake` VALUES (40, '蓝莓丹麦', 'Croissant With Blueberry Jam', '21cake「经典款', 13, '66g(一个)', './img/contImg1.jpg', 'null', 1, 1, 99, 'online', 'new', '/金黄，酥脆,内部孔洞均匀舒展/<br>/咬它的口感，像踩在雪上 /<br>/野生蓝莓，手工熬制酱心/<br>/抿一下,蓝莓酱融化在油脂香气中/ ', './detImgs/lm11.jpg');
INSERT INTO `cake` VALUES (41, '(新)卡百利', 'Strawberry Fool', '八个风味层次，让草莓', 268, '454g(1.0磅)', './img/contImg2.jpg', 'null', 1, 1, 99, 'online', 'new', '产品限量，需提前预定', './img/contItem5.jpg');
INSERT INTO `cake` VALUES (42, '(新)栗蓉暗香 ', 'Chestnut Cream', '新栗上市，栗香正浓', 198, '454g(1.0磅)', './img/contImg3.jpg', 'null', 1, 1, 99, 'online', 'new', '/栗子烘烤的蛋糕坯，鲜栗蓉，点缀手工比利时黑巧克力豆/<br>Chestnuts and real fresh cream go so well together you know this isn’', './detImgs/lr12.jpg');
INSERT INTO `cake` VALUES (43, '深爱', 'Deep Bailey Lovers', '你深爱过吗？', 268, '454g(1.0磅)', './img/contImg5.jpg', 'null', 1, 1, 99, 'online', 'Popularity', '/奶油中调入玫瑰甘露，整体色泽加深/<br>/夹心中增加可咀嚼的玫瑰蜜饯，丰富口感/<br>*玫瑰花瓣经过消毒处理，仅用作装饰使用（使用围边纸与蛋糕隔开），不可食用。<br>1月1日起夹心为草莓。', './detImgs/sa12.jpg');
INSERT INTO `cake` VALUES (44, '芒果奶油', 'Mango Cream Cake', '坚持自然成熟，应季鲜', 198, '908g(2.0磅)', './img/contImg6.jpg', 'null', 1, 1, 99, 'online', 'Popularity', '/不使用罐头水果和植混奶油/<br>/坚持自然成熟，应季鲜切芒果/<br>/坚持自然成熟，应季鲜切芒果/<br>/新西兰纯乳脂奶油/<br>/自研芒果百香果慕斯夹心/<br>高价值，平价水果蛋糕，21', './detImgs/mg10.jpg');
INSERT INTO `cake` VALUES (45, '米道', 'Rice Cake', '天然、天真是这款蛋糕', 298, '454g(1.0磅)', './img/contImg7.jpg', 'null', 1, 1, 99, 'online', 'Popularity', '天真、天然<br>是我们做这款蛋糕唯一的出发点', './detImgs/md1.jpg');
INSERT INTO `cake` VALUES (46, '榴莲飘飘', 'A Picture of Durian Grey', '严格捍卫榴莲狂热者的', 298, '908g(2.0磅)', './img/contImg8.jpg', 'null', 1, 1, 99, 'online', 'Popularity', '/自然成熟的泰国榴莲/<br>/在曼谷，官兵后代庭院中，生长着一百年至一百五十年的榴莲树/<br>Imagine if an object could bear the weight of all y', './detImgs/ll11.jpg');
INSERT INTO `cake` VALUES (47, '朗姆芝士', 'Rum Cheese Cake', '香滑的乳酪与波多黎各', 198, '454g(1.0磅)', './img/contImg9.jpg', 'null', 1, 1, 99, 'online', 'Birthday', '/香滑的乳酪与打开的一瓶波多黎各朗姆酒/<br>/酒香，微苦，清新的柠檬/<br>Shiver me timbers! Here’s a rum one – but unlike most of it', './detImgs/zs12.jpg');
INSERT INTO `cake` VALUES (48, '百香果酸乳酪慕斯 ', 'Easycake', '冰淇淋口感，不同层次', 198, '454g(1.0磅)', './img/contImg10.jpg', 'null', 1, 1, 99, 'online', 'Birthday', '/何况它，有超过130种芳香/<br>/除了酸味，百香果是世界上已知，/<br>/充满芳香的水果之一。/<br>/冰淇淋口感，不同层次的酸与冰凉/<br>*本品使用木糖醇代替蔗糖，口感无差别。</br', './detImgs/ms11.jpg');
INSERT INTO `cake` VALUES (49, '彼尔德(ＨＢＤ)', 'Chocolate Mousse', '彼尔德联名款--猪年', 198, '454g(1.0磅)', './img/contImg11.jpg', 'null', 1, 1, 99, 'online', 'Birthday', '彼尔德联名款--猪年限定版', './detImgs/qkl1.jpg');

-- ----------------------------
-- Table structure for cakelable
-- ----------------------------
DROP TABLE IF EXISTS `cakelable`;
CREATE TABLE `cakelable`  (
  `id` int(3) NULL DEFAULT NULL,
  `lable` varchar(20) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = gbk COLLATE = gbk_chinese_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of cakelable
-- ----------------------------
INSERT INTO `cakelable` VALUES (1, '情侣');
INSERT INTO `cakelable` VALUES (1, '人气');
INSERT INTO `cakelable` VALUES (2, '情侣');
INSERT INTO `cakelable` VALUES (2, '人气');
INSERT INTO `cakelable` VALUES (3, '人气');
INSERT INTO `cakelable` VALUES (4, '一人份');
INSERT INTO `cakelable` VALUES (4, '人气');
INSERT INTO `cakelable` VALUES (5, '情侣');
INSERT INTO `cakelable` VALUES (5, '聚会');
INSERT INTO `cakelable` VALUES (5, '生日');
INSERT INTO `cakelable` VALUES (6, '人气');
INSERT INTO `cakelable` VALUES (6, '生日');
INSERT INTO `cakelable` VALUES (7, '聚会');
INSERT INTO `cakelable` VALUES (7, '人气');
INSERT INTO `cakelable` VALUES (7, '生日');
INSERT INTO `cakelable` VALUES (8, '儿童');
INSERT INTO `cakelable` VALUES (8, '人气');
INSERT INTO `cakelable` VALUES (8, '生日');
INSERT INTO `cakelable` VALUES (9, '情侣');
INSERT INTO `cakelable` VALUES (9, '生日');
INSERT INTO `cakelable` VALUES (10, '新品');
INSERT INTO `cakelable` VALUES (10, '人气');
INSERT INTO `cakelable` VALUES (10, '生日');
INSERT INTO `cakelable` VALUES (10, '相识');
INSERT INTO `cakelable` VALUES (11, '一人份');
INSERT INTO `cakelable` VALUES (11, '新品');
INSERT INTO `cakelable` VALUES (11, '总有一款适合你');
INSERT INTO `cakelable` VALUES (12, '儿童');
INSERT INTO `cakelable` VALUES (12, '聚会');
INSERT INTO `cakelable` VALUES (12, '长辈');
INSERT INTO `cakelable` VALUES (12, '栗子蛋糕');
INSERT INTO `cakelable` VALUES (13, '低温');
INSERT INTO `cakelable` VALUES (13, '人气');
INSERT INTO `cakelable` VALUES (14, '人气');
INSERT INTO `cakelable` VALUES (15, '人气');
INSERT INTO `cakelable` VALUES (16, 'null');
INSERT INTO `cakelable` VALUES (17, 'null');
INSERT INTO `cakelable` VALUES (18, 'null');
INSERT INTO `cakelable` VALUES (19, 'null');
INSERT INTO `cakelable` VALUES (20, 'null');
INSERT INTO `cakelable` VALUES (21, 'null');
INSERT INTO `cakelable` VALUES (22, 'null');
INSERT INTO `cakelable` VALUES (23, 'null');
INSERT INTO `cakelable` VALUES (24, 'null');
INSERT INTO `cakelable` VALUES (25, 'null');
INSERT INTO `cakelable` VALUES (26, '新品');
INSERT INTO `cakelable` VALUES (26, '吐司');
INSERT INTO `cakelable` VALUES (27, '面包');
INSERT INTO `cakelable` VALUES (27, '面包套餐');
INSERT INTO `cakelable` VALUES (28, '面包');
INSERT INTO `cakelable` VALUES (28, '面包套餐');
INSERT INTO `cakelable` VALUES (29, '面包');
INSERT INTO `cakelable` VALUES (29, '面包套餐');
INSERT INTO `cakelable` VALUES (30, '面包');
INSERT INTO `cakelable` VALUES (31, '面包');
INSERT INTO `cakelable` VALUES (31, '女性');
INSERT INTO `cakelable` VALUES (32, '面包');
INSERT INTO `cakelable` VALUES (32, '儿童');
INSERT INTO `cakelable` VALUES (33, 'null');
INSERT INTO `cakelable` VALUES (34, 'null');
INSERT INTO `cakelable` VALUES (35, 'null');
INSERT INTO `cakelable` VALUES (36, 'null');
INSERT INTO `cakelable` VALUES (37, 'null');
INSERT INTO `cakelable` VALUES (38, 'null');
INSERT INTO `cakelable` VALUES (39, 'null');
INSERT INTO `cakelable` VALUES (40, 'null');
INSERT INTO `cakelable` VALUES (41, 'null');
INSERT INTO `cakelable` VALUES (42, 'null');
INSERT INTO `cakelable` VALUES (43, 'null');
INSERT INTO `cakelable` VALUES (44, 'null');
INSERT INTO `cakelable` VALUES (45, 'null');
INSERT INTO `cakelable` VALUES (46, 'null');
INSERT INTO `cakelable` VALUES (47, 'null');
INSERT INTO `cakelable` VALUES (48, 'null');
INSERT INTO `cakelable` VALUES (49, 'null');

-- ----------------------------
-- Table structure for cakelunbo
-- ----------------------------
DROP TABLE IF EXISTS `cakelunbo`;
CREATE TABLE `cakelunbo`  (
  `id` int(3) NULL DEFAULT NULL,
  `lunboImg` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = gbk COLLATE = gbk_chinese_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of cakelunbo
-- ----------------------------
INSERT INTO `cakelunbo` VALUES (1, './fenleImg/sa1.jpg');
INSERT INTO `cakelunbo` VALUES (1, './fenleImg/sa2.jpg');
INSERT INTO `cakelunbo` VALUES (1, './fenleImg/sa3.jpg');
INSERT INTO `cakelunbo` VALUES (1, './fenleImg/sa4.jpg');
INSERT INTO `cakelunbo` VALUES (1, './fenleImg/sa5.jpg');
INSERT INTO `cakelunbo` VALUES (2, './fenleImg/cmny1.jpg');
INSERT INTO `cakelunbo` VALUES (2, './fenleImg/cmny2.jpg');
INSERT INTO `cakelunbo` VALUES (3, './fenleImg/hyj1.jpg');
INSERT INTO `cakelunbo` VALUES (3, './fenleImg/hyj2.jpg');
INSERT INTO `cakelunbo` VALUES (3, './fenleImg/hyj3.jpg');
INSERT INTO `cakelunbo` VALUES (3, './fenleImg/hyj4.jpg');
INSERT INTO `cakelunbo` VALUES (3, './fenleImg/hyj5.jpg');
INSERT INTO `cakelunbo` VALUES (4, './fenleImg/blk1.jpg');
INSERT INTO `cakelunbo` VALUES (4, './fenleImg/blk2.jpg');
INSERT INTO `cakelunbo` VALUES (4, './fenleImg/blk3.jpg');
INSERT INTO `cakelunbo` VALUES (4, './fenleImg/blk4.jpg');
INSERT INTO `cakelunbo` VALUES (5, './fenleImg/ny1.jpg');
INSERT INTO `cakelunbo` VALUES (5, './fenleImg/ny2.jpg');
INSERT INTO `cakelunbo` VALUES (5, './fenleImg/ny3.jpg');
INSERT INTO `cakelunbo` VALUES (5, './fenleImg/ny4.jpg');
INSERT INTO `cakelunbo` VALUES (6, './fenleImg/llpp1.jpg');
INSERT INTO `cakelunbo` VALUES (7, './fenleImg/hbqklms1.png');
INSERT INTO `cakelunbo` VALUES (8, './fenleImg/md1.jpg');
INSERT INTO `cakelunbo` VALUES (8, './fenleImg/md2.jpg');
INSERT INTO `cakelunbo` VALUES (8, './fenleImg/md3.jpg');
INSERT INTO `cakelunbo` VALUES (8, './fenleImg/md4.jpg');
INSERT INTO `cakelunbo` VALUES (8, './fenleImg/md5.jpg');
INSERT INTO `cakelunbo` VALUES (9, './fenleImg/lmzh1.jpg');
INSERT INTO `cakelunbo` VALUES (9, './fenleImg/lmzh2.jpg');
INSERT INTO `cakelunbo` VALUES (9, './fenleImg/lmzh3.jpg');
INSERT INTO `cakelunbo` VALUES (10, './fenleImg/qc1.jpg');
INSERT INTO `cakelunbo` VALUES (10, './fenleImg/qc2.jpg');
INSERT INTO `cakelunbo` VALUES (10, './fenleImg/qc3.jpg');
INSERT INTO `cakelunbo` VALUES (10, './fenleImg/qc4.jpg');
INSERT INTO `cakelunbo` VALUES (10, './fenleImg/qc5.jpg');
INSERT INTO `cakelunbo` VALUES (11, './fenleImg/mocha1.jpg');
INSERT INTO `cakelunbo` VALUES (11, './fenleImg/mocha2.jpg');
INSERT INTO `cakelunbo` VALUES (11, './fenleImg/mocha3.jpg');
INSERT INTO `cakelunbo` VALUES (11, './fenleImg/mocha4.jpg');
INSERT INTO `cakelunbo` VALUES (12, './fenleImg/lrax1.jpg');
INSERT INTO `cakelunbo` VALUES (12, './fenleImg/lrax2.jpg');
INSERT INTO `cakelunbo` VALUES (12, './fenleImg/lrax3.jpg');
INSERT INTO `cakelunbo` VALUES (12, './fenleImg/lrax4.jpg');
INSERT INTO `cakelunbo` VALUES (13, './fenleImg/gybqldg1.jpg');
INSERT INTO `cakelunbo` VALUES (14, './fenleImg/ywnrbql1.jpg');
INSERT INTO `cakelunbo` VALUES (15, './fenleImg/xrzh1.jpg');
INSERT INTO `cakelunbo` VALUES (16, './fenleImg/lzbql1.jpg');
INSERT INTO `cakelunbo` VALUES (16, './fenleImg/lzbql2.jpg');
INSERT INTO `cakelunbo` VALUES (16, './fenleImg/lzbql3.jpg');
INSERT INTO `cakelunbo` VALUES (17, './fenleImg/llbql1.jpg');
INSERT INTO `cakelunbo` VALUES (18, './fenleImg/mymg1.jpg');
INSERT INTO `cakelunbo` VALUES (19, './fenleImg/hz1.jpg');
INSERT INTO `cakelunbo` VALUES (20, './fenleImg/sbzpdyg1.jpg');
INSERT INTO `cakelunbo` VALUES (21, './fenleImg/sbzpdyg1.jpg');
INSERT INTO `cakelunbo` VALUES (22, './fenleImg/yjxfgekf1.jpg');
INSERT INTO `cakelunbo` VALUES (22, './fenleImg/yjxfgekf2.jpg');
INSERT INTO `cakelunbo` VALUES (22, './fenleImg/yjxfgekf3.jpg');
INSERT INTO `cakelunbo` VALUES (22, './fenleImg/yjxfgekf4.jpg');
INSERT INTO `cakelunbo` VALUES (23, './fenleImg/xdmgekf1.jpg');
INSERT INTO `cakelunbo` VALUES (23, './fenleImg/xdmgekf2.jpg');
INSERT INTO `cakelunbo` VALUES (23, './fenleImg/xdmgekf3.jpg');
INSERT INTO `cakelunbo` VALUES (23, './fenleImg/xdmgekf4.jpg');
INSERT INTO `cakelunbo` VALUES (24, './fenleImg/bxgekf1.jpg');
INSERT INTO `cakelunbo` VALUES (24, './fenleImg/bxgekf2.jpg');
INSERT INTO `cakelunbo` VALUES (24, './fenleImg/bxgekf3.jpg');
INSERT INTO `cakelunbo` VALUES (24, './fenleImg/bxgekf4.jpg');
INSERT INTO `cakelunbo` VALUES (25, './fenleImg/bbyxjnygekf2.jpg');
INSERT INTO `cakelunbo` VALUES (25, './fenleImg/bbyxjnygekf3.jpg');
INSERT INTO `cakelunbo` VALUES (25, './fenleImg/bbyxjnygekf4.jpg');
INSERT INTO `cakelunbo` VALUES (25, './fenleImg/bbyxjnygekf4.jpg');
INSERT INTO `cakelunbo` VALUES (26, './fenleImg/xwctc1.jpg');
INSERT INTO `cakelunbo` VALUES (26, './fenleImg/xwctc2.jpg');
INSERT INTO `cakelunbo` VALUES (26, './fenleImg/xwctc3.jpg');
INSERT INTO `cakelunbo` VALUES (26, './fenleImg/xwctc4.jpg');
INSERT INTO `cakelunbo` VALUES (27, './fenleImg/jdtc1.jpg');
INSERT INTO `cakelunbo` VALUES (27, './fenleImg/jdtc2.jpg');
INSERT INTO `cakelunbo` VALUES (27, './fenleImg/jdtc3.jpg');
INSERT INTO `cakelunbo` VALUES (27, './fenleImg/jdtc4.jpg');
INSERT INTO `cakelunbo` VALUES (28, './fenleImg/ettc1.jpg');
INSERT INTO `cakelunbo` VALUES (28, './fenleImg/ettc2.jpg');
INSERT INTO `cakelunbo` VALUES (28, './fenleImg/ettc3.jpg');
INSERT INTO `cakelunbo` VALUES (28, './fenleImg/ettc4.jpg');
INSERT INTO `cakelunbo` VALUES (29, './fenleImg/qjftc1.jpg');
INSERT INTO `cakelunbo` VALUES (29, './fenleImg/qjftc2.jpg');
INSERT INTO `cakelunbo` VALUES (29, './fenleImg/qjftc3.jpg');
INSERT INTO `cakelunbo` VALUES (29, './fenleImg/qjftc4.jpg');
INSERT INTO `cakelunbo` VALUES (30, './fenleImg/jcmb1.jpg');
INSERT INTO `cakelunbo` VALUES (30, './fenleImg/jcmb2.jpg');
INSERT INTO `cakelunbo` VALUES (30, './fenleImg/jcmb3.jpg');
INSERT INTO `cakelunbo` VALUES (31, './fenleImg/hthzgyor1.jpg');
INSERT INTO `cakelunbo` VALUES (31, './fenleImg/hthzgyor2.jpg');
INSERT INTO `cakelunbo` VALUES (31, './fenleImg/hthzgyor3.jpg');
INSERT INTO `cakelunbo` VALUES (31, './fenleImg/hthzgyor4.jpg');
INSERT INTO `cakelunbo` VALUES (32, './fenleImg/bhdts1.jpg');
INSERT INTO `cakelunbo` VALUES (32, './fenleImg/bhdts2.jpg');
INSERT INTO `cakelunbo` VALUES (32, './fenleImg/bhdts3.jpg');
INSERT INTO `cakelunbo` VALUES (33, './fenleImg/bdgqp1.jpg');
INSERT INTO `cakelunbo` VALUES (33, './fenleImg/bdgqp2.jpg');
INSERT INTO `cakelunbo` VALUES (33, './fenleImg/bdgqp3.jpg');
INSERT INTO `cakelunbo` VALUES (33, './fenleImg/bdgqp4.jpg');
INSERT INTO `cakelunbo` VALUES (34, './fenleImg/bdgqp8.jpg');
INSERT INTO `cakelunbo` VALUES (34, './fenleImg/bdgqp9.jpg');
INSERT INTO `cakelunbo` VALUES (34, './fenleImg/bdgqp10.jpg');
INSERT INTO `cakelunbo` VALUES (34, './fenleImg/bdgqp11.jpg');
INSERT INTO `cakelunbo` VALUES (35, './fenleImg/bdgqp14.jpg');
INSERT INTO `cakelunbo` VALUES (35, './fenleImg/bdgqp15.jpg');
INSERT INTO `cakelunbo` VALUES (35, './fenleImg/bdgqp16.jpg');
INSERT INTO `cakelunbo` VALUES (36, './fenleImg/sjszzs1.jpg');
INSERT INTO `cakelunbo` VALUES (36, './fenleImg/sjszzs2.jpg');
INSERT INTO `cakelunbo` VALUES (36, './fenleImg/sjszzs3.jpg');
INSERT INTO `cakelunbo` VALUES (36, './fenleImg/sjszzs4.jpg');
INSERT INTO `cakelunbo` VALUES (37, './fenleImg/fxlz1.jpg');
INSERT INTO `cakelunbo` VALUES (38, './fenleImg/sdllz1.jpg');
INSERT INTO `cakelunbo` VALUES (39, './fenleImg/cj1.jpg');
INSERT INTO `cakelunbo` VALUES (40, './detImgs/lm1.jpg');
INSERT INTO `cakelunbo` VALUES (40, './detImgs/lm2.jpg');
INSERT INTO `cakelunbo` VALUES (40, './detImgs/lm3.jpg');
INSERT INTO `cakelunbo` VALUES (41, './detImgs/ny1.jpg');
INSERT INTO `cakelunbo` VALUES (41, './detImgs/ny2.jpg');
INSERT INTO `cakelunbo` VALUES (41, './detImgs/ny3.jpg');
INSERT INTO `cakelunbo` VALUES (41, './detImgs/ny4.jpg');
INSERT INTO `cakelunbo` VALUES (42, './detImgs/lr1.jpg');
INSERT INTO `cakelunbo` VALUES (42, './detImgs/lr2.jpg');
INSERT INTO `cakelunbo` VALUES (42, './detImgs/lr3.jpg');
INSERT INTO `cakelunbo` VALUES (42, './detImgs/lr4.jpg');
INSERT INTO `cakelunbo` VALUES (43, './detImgs/sa1.jpg');
INSERT INTO `cakelunbo` VALUES (43, './detImgs/sa2.jpg');
INSERT INTO `cakelunbo` VALUES (43, './detImgs/sa3.jpg');
INSERT INTO `cakelunbo` VALUES (43, './detImgs/sa4.jpg');
INSERT INTO `cakelunbo` VALUES (43, './detImgs/sa5.jpg');
INSERT INTO `cakelunbo` VALUES (44, './detImgs/mg2.jpg');
INSERT INTO `cakelunbo` VALUES (45, './detImgs/md1.jpg');
INSERT INTO `cakelunbo` VALUES (45, './detImgs/md2.jpg');
INSERT INTO `cakelunbo` VALUES (45, './detImgs/md3.jpg');
INSERT INTO `cakelunbo` VALUES (45, './detImgs/md4.jpg');
INSERT INTO `cakelunbo` VALUES (45, './detImgs/md5.jpg');
INSERT INTO `cakelunbo` VALUES (46, './detImgs/ll1.jpg');
INSERT INTO `cakelunbo` VALUES (46, './detImgs/ll2.jpg');
INSERT INTO `cakelunbo` VALUES (47, './detImgs/zs1.jpg');
INSERT INTO `cakelunbo` VALUES (47, './detImgs/zs2.jpg');
INSERT INTO `cakelunbo` VALUES (47, './detImgs/zs3.jpg');
INSERT INTO `cakelunbo` VALUES (48, './detImgs/ms1.jpg');
INSERT INTO `cakelunbo` VALUES (48, './detImgs/ms2.gif');
INSERT INTO `cakelunbo` VALUES (48, './detImgs/ms3.jpg');
INSERT INTO `cakelunbo` VALUES (48, './detImgs/ms4.jpg');
INSERT INTO `cakelunbo` VALUES (48, './detImgs/ms5.jpg');
INSERT INTO `cakelunbo` VALUES (49, './detImgs/qkl1.jpg');
INSERT INTO `cakelunbo` VALUES (49, './detImgs/qkl2.jpg');
INSERT INTO `cakelunbo` VALUES (49, './detImgs/qkl3.jpg');

-- ----------------------------
-- Table structure for cakeshow
-- ----------------------------
DROP TABLE IF EXISTS `cakeshow`;
CREATE TABLE `cakeshow`  (
  `id` int(3) NULL DEFAULT NULL,
  `showImg` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL
) ENGINE = InnoDB CHARACTER SET = gbk COLLATE = gbk_chinese_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of cakeshow
-- ----------------------------
INSERT INTO `cakeshow` VALUES (1, './fenleImg/sa6.jpg');
INSERT INTO `cakeshow` VALUES (1, './fenleImg/sa7.jpg');
INSERT INTO `cakeshow` VALUES (1, './fenleImg/sa8.jpg');
INSERT INTO `cakeshow` VALUES (1, './fenleImg/sa9.jpg');
INSERT INTO `cakeshow` VALUES (1, './fenleImg/sa10.jpg');
INSERT INTO `cakeshow` VALUES (1, './fenleImg/sa11.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny3.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny4.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny5.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny6.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny7.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny8.jpg');
INSERT INTO `cakeshow` VALUES (2, './fenleImg/cmny9.jpg');
INSERT INTO `cakeshow` VALUES (3, './fenleImg/hyj6.jpg');
INSERT INTO `cakeshow` VALUES (3, './fenleImg/hyj7.jpg');
INSERT INTO `cakeshow` VALUES (3, './fenleImg/hyj8.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk5.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk6.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk7.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk8.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk9.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk10.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk11.jpg');
INSERT INTO `cakeshow` VALUES (4, './fenleImg/blk12.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny5.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny6.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny7.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny8.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny9.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny10.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny11.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny12.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny13.jpg');
INSERT INTO `cakeshow` VALUES (5, './fenleImg/ny14.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp2.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp3.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp4.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp5.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp6.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp7.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp8.jpg');
INSERT INTO `cakeshow` VALUES (6, './fenleImg/llpp9.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms2.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms3.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms4.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms5.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms6.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms7.jpg');
INSERT INTO `cakeshow` VALUES (7, './fenleImg/hbqklms8.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md6.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md7.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md8.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md9.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md10.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md11.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md12.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md13.jpg');
INSERT INTO `cakeshow` VALUES (8, './fenleImg/md14.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh4.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh5.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh6.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh7.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh8.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh9.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh10.jpg');
INSERT INTO `cakeshow` VALUES (9, './fenleImg/lmzh11.jpg');
INSERT INTO `cakeshow` VALUES (10, './fenleImg/qc6.jpg');
INSERT INTO `cakeshow` VALUES (10, './fenleImg/qc7.jpg');
INSERT INTO `cakeshow` VALUES (10, './fenleImg/qc8.jpg');
INSERT INTO `cakeshow` VALUES (10, './fenleImg/qc9.jpg');
INSERT INTO `cakeshow` VALUES (10, './fenleImg/qc10.jpg');
INSERT INTO `cakeshow` VALUES (10, './fenleImg/qc11.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha5.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha6.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha7.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha8.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha9.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha10.jpg');
INSERT INTO `cakeshow` VALUES (11, './fenleImg/mocha11.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax5.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax6.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax7.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax8.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax9.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax10.jpg');
INSERT INTO `cakeshow` VALUES (12, './fenleImg/lrax11.jpg');
INSERT INTO `cakeshow` VALUES (13, './fenleImg/gybqldg2.jpg');
INSERT INTO `cakeshow` VALUES (13, './fenleImg/gybqldg3.jpg');
INSERT INTO `cakeshow` VALUES (13, './fenleImg/gybqldg4.jpg');
INSERT INTO `cakeshow` VALUES (13, './fenleImg/gybqldg5.jpg');
INSERT INTO `cakeshow` VALUES (13, './fenleImg/gybqldg6.jpg');
INSERT INTO `cakeshow` VALUES (13, './fenleImg/gybqldg7.jpg');
INSERT INTO `cakeshow` VALUES (14, './fenleImg/ywnrbql2.jpg');
INSERT INTO `cakeshow` VALUES (14, './fenleImg/ywnrbql3.jpg');
INSERT INTO `cakeshow` VALUES (14, './fenleImg/ywnrbql4.png');
INSERT INTO `cakeshow` VALUES (15, './fenleImg/xrzh2.jpg');
INSERT INTO `cakeshow` VALUES (15, './fenleImg/xrzh3.jpg');
INSERT INTO `cakeshow` VALUES (15, './fenleImg/xrzh4.jpg');
INSERT INTO `cakeshow` VALUES (15, './fenleImg/xrzh5.jpg');
INSERT INTO `cakeshow` VALUES (15, './fenleImg/xrzh6.jpg');
INSERT INTO `cakeshow` VALUES (15, './fenleImg/xrzh7.jpg');
INSERT INTO `cakeshow` VALUES (16, './fenleImg/lzbql4.jpg');
INSERT INTO `cakeshow` VALUES (16, './fenleImg/lzbql5.jpg');
INSERT INTO `cakeshow` VALUES (16, './fenleImg/lzbql6.jpg');
INSERT INTO `cakeshow` VALUES (17, './fenleImg/llbql2.jpg');
INSERT INTO `cakeshow` VALUES (17, './fenleImg/llbql3.jpg');
INSERT INTO `cakeshow` VALUES (17, './fenleImg/llbql4.png');
INSERT INTO `cakeshow` VALUES (18, './fenleImg/mymg2.jpg');
INSERT INTO `cakeshow` VALUES (18, './fenleImg/mymg3.jpg');
INSERT INTO `cakeshow` VALUES (18, './fenleImg/mymg4.jpg');
INSERT INTO `cakeshow` VALUES (18, './fenleImg/mymg5.jpg');
INSERT INTO `cakeshow` VALUES (18, './fenleImg/mymg6.jpg');
INSERT INTO `cakeshow` VALUES (19, './fenleImg/hz2.jpg');
INSERT INTO `cakeshow` VALUES (19, './fenleImg/hz3.jpg');
INSERT INTO `cakeshow` VALUES (19, './fenleImg/hz4.jpg');
INSERT INTO `cakeshow` VALUES (20, './fenleImg/sbzpdyg2.jpg');
INSERT INTO `cakeshow` VALUES (20, './fenleImg/sbzpdyg3.jpg');
INSERT INTO `cakeshow` VALUES (20, './fenleImg/sbzpdyg4.jpg');
INSERT INTO `cakeshow` VALUES (20, './fenleImg/sbzpdyg5.jpg');
INSERT INTO `cakeshow` VALUES (21, './fenleImg/sbzpdyg2.jpg');
INSERT INTO `cakeshow` VALUES (21, './fenleImg/sbzpdyg3.jpg');
INSERT INTO `cakeshow` VALUES (21, './fenleImg/sbzpdyg4.jpg');
INSERT INTO `cakeshow` VALUES (21, './fenleImg/sbzpdyg5.jpg');
INSERT INTO `cakeshow` VALUES (22, './fenleImg/yjxfgekf5.jpg');
INSERT INTO `cakeshow` VALUES (22, './fenleImg/yjxfgekf6.jpg');
INSERT INTO `cakeshow` VALUES (22, './fenleImg/yjxfgekf7.jpg');
INSERT INTO `cakeshow` VALUES (22, './fenleImg/yjxfgekf8.jpg');
INSERT INTO `cakeshow` VALUES (23, './fenleImg/xdmgekf5.jpg');
INSERT INTO `cakeshow` VALUES (23, './fenleImg/xdmgekf6.jpg');
INSERT INTO `cakeshow` VALUES (23, './fenleImg/xdmgekf7.jpg');
INSERT INTO `cakeshow` VALUES (23, './fenleImg/xdmgekf8.jpg');
INSERT INTO `cakeshow` VALUES (24, './fenleImg/bxgekf5.jpg');
INSERT INTO `cakeshow` VALUES (24, './fenleImg/bxgekf6.jpg');
INSERT INTO `cakeshow` VALUES (24, './fenleImg/bxgekf7.jpg');
INSERT INTO `cakeshow` VALUES (24, './fenleImg/bxgekf8.jpg');
INSERT INTO `cakeshow` VALUES (25, './fenleImg/bbyxjnygekf6.jpg');
INSERT INTO `cakeshow` VALUES (25, './fenleImg/bbyxjnygekf7.jpg');
INSERT INTO `cakeshow` VALUES (25, './fenleImg/bbyxjnygekf8.jpg');
INSERT INTO `cakeshow` VALUES (25, './fenleImg/bbyxjnygekf5.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc5.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc6.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc7.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc8.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc9.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc10.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc11.jpg');
INSERT INTO `cakeshow` VALUES (26, './fenleImg/xwctc12.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc5.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc6.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc7.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc8.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc9.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc10.jpg');
INSERT INTO `cakeshow` VALUES (27, './fenleImg/jdtc11.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc5.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc6.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc7.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc8.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc9.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc10.jpg');
INSERT INTO `cakeshow` VALUES (28, './fenleImg/ettc11.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc5.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc6.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc7.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc8.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc9.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc10.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc11.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc12.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc13.jpg');
INSERT INTO `cakeshow` VALUES (29, './fenleImg/qjftc14.jpg');
INSERT INTO `cakeshow` VALUES (30, './fenleImg/jcmb4.jpg');
INSERT INTO `cakeshow` VALUES (30, './fenleImg/jcmb5.jpg');
INSERT INTO `cakeshow` VALUES (30, './fenleImg/jcmb6.jpg');
INSERT INTO `cakeshow` VALUES (30, './fenleImg/jcmb7.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor5.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor6.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor7.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor8.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor9.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor1.jpg');
INSERT INTO `cakeshow` VALUES (31, './fenleImg/hthzgyor1.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts4.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts5.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts6.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts7.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts8.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts9.jpg');
INSERT INTO `cakeshow` VALUES (32, './fenleImg/bhdts10.jpg');
INSERT INTO `cakeshow` VALUES (33, './fenleImg/bdgqp5.jpg');
INSERT INTO `cakeshow` VALUES (33, './fenleImg/bdgqp6.jpg');
INSERT INTO `cakeshow` VALUES (33, './fenleImg/bdgqp7.jpg');
INSERT INTO `cakeshow` VALUES (34, './fenleImg/bdgqp12.jpg');
INSERT INTO `cakeshow` VALUES (34, './fenleImg/bdgqp13.jpg');
INSERT INTO `cakeshow` VALUES (35, './fenleImg/bdgqp17.jpg');
INSERT INTO `cakeshow` VALUES (35, './fenleImg/bdgqp18.jpg');
INSERT INTO `cakeshow` VALUES (35, './fenleImg/bdgqp19.jpg');
INSERT INTO `cakeshow` VALUES (36, './fenleImg/sjszzs5.jpg');
INSERT INTO `cakeshow` VALUES (36, './fenleImg/sjszzs6.jpg');
INSERT INTO `cakeshow` VALUES (36, './fenleImg/sjszzs7.jpg');
INSERT INTO `cakeshow` VALUES (36, './fenleImg/sjszzs8.jpg');
INSERT INTO `cakeshow` VALUES (36, './fenleImg/sjszzs9.jpg');
INSERT INTO `cakeshow` VALUES (37, './fenleImg/fxlz2.jpg');
INSERT INTO `cakeshow` VALUES (38, './fenleImg/sdllz2.jpg');
INSERT INTO `cakeshow` VALUES (38, './fenleImg/sdllz3.jpg');
INSERT INTO `cakeshow` VALUES (38, './fenleImg/sdllz4.jpg');
INSERT INTO `cakeshow` VALUES (39, './fenleImg/cj2.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm4.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm5.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm6.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm7.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm8.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm9.jpg');
INSERT INTO `cakeshow` VALUES (40, './detImgs/lm10.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny5.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny6.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny7.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny8.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny9.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny10.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny11.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny12.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny13.jpg');
INSERT INTO `cakeshow` VALUES (41, './detImgs/ny14.jpg');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr5.jpg');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr6.jpg');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr7.jpg');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr8.jpg');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr9.jpg');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr10.png');
INSERT INTO `cakeshow` VALUES (42, './detImgs/lr11.jpg');
INSERT INTO `cakeshow` VALUES (43, './detImgs/sa6.jpg');
INSERT INTO `cakeshow` VALUES (43, './detImgs/sa7.jpg');
INSERT INTO `cakeshow` VALUES (43, './detImgs/sa8.jpg');
INSERT INTO `cakeshow` VALUES (43, './detImgs/sa9.jpg');
INSERT INTO `cakeshow` VALUES (43, './detImgs/sa10.jpg');
INSERT INTO `cakeshow` VALUES (43, './detImgs/sa11.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg2.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg3.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg4.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg5.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg6.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg7.jpg');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg8.png');
INSERT INTO `cakeshow` VALUES (44, './detImgs/mg9.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md6.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md7.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md8.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md9.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md10.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md11.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md12.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md13.jpg');
INSERT INTO `cakeshow` VALUES (45, './detImgs/md14.png');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll3.jpg');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll4.jpg');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll5.jpg');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll6.jpg');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll7.jpg');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll8.jpg');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll9.png');
INSERT INTO `cakeshow` VALUES (46, './detImgs/ll10.jpg');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs4.jpg');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs5.jpg');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs6.jpg');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs7.jpg');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs8.jpg');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs9.png');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs10.png');
INSERT INTO `cakeshow` VALUES (47, './detImgs/zs11.jpg');
INSERT INTO `cakeshow` VALUES (48, './detImgs/ms6.jpg');
INSERT INTO `cakeshow` VALUES (48, './detImgs/ms7.jpg');
INSERT INTO `cakeshow` VALUES (48, './detImgs/ms8.jpg');
INSERT INTO `cakeshow` VALUES (48, './detImgs/ms9.jpg');
INSERT INTO `cakeshow` VALUES (48, './detImgs/ms10.png');
INSERT INTO `cakeshow` VALUES (49, './detImgs/qkl4.gif');
INSERT INTO `cakeshow` VALUES (49, './detImgs/qkl5.jpg');
INSERT INTO `cakeshow` VALUES (49, './detImgs/qkl6.png');

SET FOREIGN_KEY_CHECKS = 1;
